version: '3.5'
services:
  database:
    image: postgres:15
    container_name: postgres_testcase
    env_file:
      - .env-prod
    ports:
      - 8090:5432
    restart: unless-stopped
    volumes:
      - postgresql_prod_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ['docker/app.sh']
    env_file:
      - .env-prod
    ports:
      - 8080:8000
    restart: unless-stopped
    depends_on:
      - database

volumes:
  postgresql_prod_data: null
