version: '3.5'
services:
  database:
    image: postgres:15
    container_name: postgres_testcase
    env_file:
      - .env-prod
    ports:
      - 8090:5432
    restart: unless-stopped
  app:
    build:
      context: .
    container_name: fastapi_app
    command: ['docker/app.sh']
    env_file:
      - .env-prod
    ports:
      - 8080:8000
    restart: unless-stopped
    depends_on:
      - database
networks:
  default:
    driver: bridge
    name: webnet
