"""Add field in table questions

Revision ID: 48ac7351a7c6
Revises: 48e942bf6a36
Create Date: 2023-10-17 01:43:29.817729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ac7351a7c6'
down_revision: Union[str, None] = '48e942bf6a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('id_api', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'questions', ['id_api'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'id_api')
    # ### end Alembic commands ###
